const asyncHandler = require('express-async-handler');
const Make = require('../models/Make');
const Model = require('../models/Model');
const Product = require('../models/Product');
const generateSlug = require('../utils/generateSlug');

// @desc    Fetch all makes
// @route   GET /api/makes
// @access  Public
const getMakes = asyncHandler(async (req, res) => {
    const makes = await Make.find({ isActive: true }).populate('categories', 'name slug');
    res.json(makes);
});

// @desc    Get make by slug
// @route   GET /api/makes/:slug
// @access  Public
const getMakeBySlug = asyncHandler(async (req, res) => {
    const make = await Make.findOne({ slug: req.params.slug, isActive: true })
        .populate('categories', 'name slug');

    if (make) {
        res.json(make);
    } else {
        res.status(404);
        throw new Error('Make not found');
    }
});

// @desc    Get makes by category
// @route   GET /api/makes/category/:categoryId
// @access  Public
const getMakesByCategory = asyncHandler(async (req, res) => {
    const makes = await Make.find({
        categories: req.params.categoryId,
        isActive: true
    }).populate('categories', 'name slug');

    res.json(makes);
});

// @desc    Create a make
// @route   POST /api/makes
// @access  Private/Admin
const createMake = asyncHandler(async (req, res) => {
    const { name, description, logo, categories } = req.body;

    const makeExists = await Make.findOne({ name });

    if (makeExists) {
        res.status(400);
        throw new Error('Make already exists');
    }

    // Generate slug if not provided
    var slug = await generateSlug(name, Make);

    const make = await Make.create({
        name,
        description,
        logo,
        categories: categories || [],
        isActive: true,
        slug: slug
    });

    res.status(201).json(make);
});

// @desc    Update a make
// @route   PUT /api/makes/:id
// @access  Private/Admin
const updateMake = asyncHandler(async (req, res) => {
    const { name, description, logo, isActive, categories } = req.body;

    const make = await Make.findById(req.params.id);

    if (make) {
        // Check if new name conflicts with existing make (excluding current)
        if (name && name !== make.name) {
            const nameExists = await Make.findOne({ name });
            if (nameExists) {
                res.status(400);
                throw new Error('Make name already exists');
            }
        }

        make.name = name || make.name;
        make.description = description !== undefined ? description : make.description;
        make.logo = logo !== undefined ? logo : make.logo;
        make.isActive = isActive !== undefined ? isActive : make.isActive;
        make.categories = categories !== undefined ? categories : make.categories;

        // Regenerate slug if name changed
        if (name && name !== make.name) {
            make.slug = undefined; // Will be regenerated by pre-save hook
        }

        const updatedMake = await make.save();
        res.json(updatedMake);
    } else {
        res.status(404);
        throw new Error('Make not found');
    }
});

// @desc    Delete a make
// @route   DELETE /api/makes/:id
// @access  Private/Admin
const deleteMake = asyncHandler(async (req, res) => {
    const make = await Make.findById(req.params.id);

    if (make) {
        // Check if make has models
        const models = await Model.find({ make: req.params.id });
        if (models.length > 0) {
            res.status(400);
            throw new Error('Cannot delete make with associated models. Delete models first.');
        }

        // Check if make has products
        const products = await Product.find({ make: req.params.id });
        if (products.length > 0) {
            res.status(400);
            throw new Error('Cannot delete make with associated products. Remove or reassign products first.');
        }

        await make.deleteOne();
        res.json({ message: 'Make removed' });
    } else {
        res.status(404);
        throw new Error('Make not found');
    }
});

module.exports = {
    getMakes,
    getMakeBySlug,
    getMakesByCategory,
    createMake,
    updateMake,
    deleteMake,
};
